---
name: Omada Controller
version: 0.0.1
slug: omada_controller
description: TP-Link Omada Controller Add-On for Home Assistant
arch: 
  - amd64
  - armv7l
  - arm64
startup: application
webui: https://[HOST]:[PORT:8043]
boot: auto
ports:
  8088/tcp: 8088
  8043/tcp: 8043
  8843/typ: 8843
  27001/udp: 27001
  29810/udp: 29810
  29811/tcp: 29811
  29812/tcp: 29812
  29813/tcp: 29813
  29814/tcp: 29814
ports_description:
  8088/tcp: Management portal HTTP port
  8043/tcp: Management portal HTTPS port
  8843/typ: User portal HTTPS port
  27001/udp: Omada Controller can be discovered by the Omada APP within the same network through this port
  29810/udp: Omada Controller and Omada Discovery Utility discover Omada devices
  29811/tcp: Omada Controller and Omada Discovery Utility manage the Omada devices running firmware fully adapted to Omada Controller v4*
  29812/tcp: Omada Controller and Omada Discovery Utility manage the Omada devices running firmware fully adapted to Omada Controller v4*
  29813/tcp: When upgrading the firmware for the Omada devices running firmware fully adapted to Omada Controller v4*
  29814/tcp: Omada Controller and Omada Discovery Utility manage the Omada devices running firmware fully adapted to Omada Controller v5*
environment:
  MANAGE_HTTP_PORT: 8088
  MANAGE_HTTPS_PORT: 8043
  PORTAL_HTTP_PORT: 8088
  PORTAL_HTTPS_PORT: 8843
  SHOW_SERVER_LOGS: true
  SHOW_MONGODB_LOGS: false
  SMALL_FILES: false
  SSL_CERT_NAME: tls.crt
  SSL_KEY_NAME: tls.key
  TZ: Etc/UTC